// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-banner/Desktop.tsx": () => import("../components/mockups/hero-banner/Desktop.tsx"),
  "./components/mockups/hero-banner/Mobile.tsx": () => import("../components/mockups/hero-banner/Mobile.tsx"),
  "./components/mockups/hero-v4/HeroMockup.tsx": () => import("../components/mockups/hero-v4/HeroMockup.tsx"),
  "./components/mockups/homepage/HomepageRedesign.tsx": () => import("../components/mockups/homepage/HomepageRedesign.tsx"),
  "./components/mockups/homepage/HomepageV4.tsx": () => import("../components/mockups/homepage/HomepageV4.tsx")
};
