import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import variantsRouter from "./variants";
import searchRouter from "./search";
import reviewsRouter from "./reviews";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import notificationsRouter from "./notifications";
import pushSubscriptionsRouter from "./push-subscriptions";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import sellerApplicationsRouter from "./seller-applications";
import sellersRouter from "./sellers";
import messagingRouter from "./messaging";
import couriersRouter from "./couriers";
import deliveryZonesRouter from "./delivery-zones";
import recoveryCheckRouter from "./recovery-check";
import heroBannersRouter from "./hero-banners";
import wishlistRouter from "./wishlist";
import supportRouter from "./support";
import contactFormRouter from "./contact-form";
import deliveryMissionsRouter from "./delivery-missions";
import courierAvailabilityRouter from "./courier-availability";
import missionOffersRouter from "./mission-offers";
import courierLocationRouter from "./courier-location";
import trackingRouter from "./tracking";
import courierOpsRouter from "./courier-ops";
import courierWalletRouter from "./courier-wallet";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(searchRouter);
router.use(productsRouter);
router.use(variantsRouter);
router.use(reviewsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(notificationsRouter);
router.use(pushSubscriptionsRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(sellerApplicationsRouter);
router.use(sellersRouter);
router.use(messagingRouter);
router.use(trackingRouter);
router.use(courierOpsRouter);
router.use(courierWalletRouter);
router.use(courierLocationRouter);
router.use(couriersRouter);
router.use(deliveryZonesRouter);
router.use(heroBannersRouter);
router.use(wishlistRouter);
router.use(contactFormRouter);
router.use(supportRouter);
router.use(deliveryMissionsRouter);
router.use(missionOffersRouter);
router.use(courierAvailabilityRouter);
router.use(recoveryCheckRouter);

export default router;
